const images={
    titleImg:require('./images/Welcome/title.png'),
    eye:require('./images/Welcome/eye.png'),
    heart:require('./images/Welcome/Heart.png'),
    playFilled:require('./images/Welcome/PlayFilled.png'),
    burgerMenu:require('./images/Home/BurgerMenu.png'),
    bell:require('./images/Home/Bell.png'),
    apple:require('./images/Home/Apple.png'),
    gmail:require('./images/Home/Gmail.png'),
    facebook:require('./images/Home/Facebook.png'),
    search:require('./images/Home/Search.png'),
    emptyProfileImg:require('./images/Home/BlankImg.png'),
    left:require('./images/Profile/Left.png'),
    right:require('./images/Profile/Right.png'),
    more:require('./images/Profile/More.png'),
    lamp:require('./images/splash/Lamp.png'),
    light:require('./images/splash/Light.png'),
    lightEffect:require('./images/splash/LightEffect.png'),
    splash:require('./images/splash.png'),
    test:require('./images/Test/Test.png'),
    review:require('./images/Test/Review.png'),
    rotate:require('./images/Test/Rotate.png'),
    timer:require('./images/Test/Timer.png'),
    share:require('./images/Test/Share.png'),
    pic1:require('./images/Test/Pic1.png'),
    pic2:require('./images/Test/Pic2.png'),
    pic3:require('./images/Test/Pic3.png'),
    firstPlaceBg:require('./images/Test/First.png'),
    secondPlaceBg:require('./images/Test/Second.png'),
    thirdPlaceBg:require('./images/Test/Third.png'),
}

export default images;